import re
from dataclasses import dataclass


@dataclass
class ModerationResult:
    status: str
    score: float
    reason: str


PROHIBITED_WORDS = {
    # Direct threats / violence
    "i will kill you",
    "i'm going to kill you",
    "im going to kill you",
    "i will hurt you",
    "i'm going to hurt you",
    "im going to hurt you",
    "i will find you",
    "i'm going to find you",
    "im going to find you",
    "i will come after you",
    "watch your back",
    "you are dead",
    "youre dead",
    "you are done",
    "i will beat you up",
    "i'm going to beat you up",
    "im going to beat you up",
    "i will stab you",
    "i'm going to stab you",
    "im going to stab you",
    "i will shoot you",
    "i'm going to shoot you",
    "im going to shoot you",

    # Self-harm encouragement
    "kill yourself",
    "go kill yourself",
    "go die",
    "you should die",
    "nobody would miss you",
    "the world would be better without you",

    # Extreme harassment / dehumanization
    "piece of shit",
    "human garbage",
    "waste of space",
    "worthless human",
    "worthless piece of shit",
    "you are worthless",
    "youre worthless",
    "you are pathetic",
    "youre pathetic",
    "disgusting piece of shit",

    # Severe profanity / direct abuse
    "fuck you",
    "fuck off",
    "shut the fuck up",
    "shut the hell up",
    "dumb piece of shit",
    "stupid piece of shit",
    "bitch",
    "son of a bitch",
    "asshole",
    "motherfucker",
    "dumbass",
    "jackass",
    "bastard",

    # Sexual harassment / explicit abuse
    "suck my dick",
    "eat shit",
    "get fucked",
    "dumb bitch",
    "stupid bitch",

    # Add your private internal slur list separately
    "2g1c",
    "2 girls 1 cup",
    "acrotomophilia",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "anilingus",
    "anus",
    "apeshit",
    "arsehole",
    "ass",
    "asshole",
    "assmunch",
    "auto erotic",
    "autoerotic",
    "babeland",
    "baby batter",
    "baby juice",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "bangbros",
    "bangbus",
    "bareback",
    "barely legal",
    "barenaked",
    "bastard",
    "bastardo",
    "bastinado",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beaver cleaver",
    "beaver lips",
    "beastiality",
    "bestiality",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bimbos",
    "birdlock",
    "bitch",
    "bitches",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blowjob",
    "blow job",
    "blow your load",
    "blue waffle",
    "blumpkin",
    "bollocks",
    "bondage",
    "boner",
    "boob",
    "boobs",
    "booty call",
    "brown showers",
    "brunette action",
    "bukkake",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bung hole",
    "bunghole",
    "busty",
    "butt",
    "buttcheeks",
    "butthole",
    "camel toe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "chocolate rosebuds",
    "cialis",
    "circlejerk",
    "cleveland steamer",
    "clit",
    "clitoris",
    "clover clamps",
    "clusterfuck",
    "cock",
    "cocks",
    "coprolagnia",
    "coprophilia",
    "cornhole",
    "coon",
    "coons",
    "creampie",
    "cum",
    "cumming",
    "cumshot",
    "cumshots",
    "cunnilingus",
    "cunt",
    "darkie",
    "date rape",
    "daterape",
    "deep throat",
    "deepthroat",
    "dendrophilia",
    "dick",
    "dildo",
    "dingleberry",
    "dingleberries",
    "dirty pillows",
    "dirty sanchez",
    "doggie style",
    "doggiestyle",
    "doggy style",
    "doggystyle",
    "dog style",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "donkey punch",
    "double dong",
    "double penetration",
    "dp action",
    "dry hump",
    "dvda",
    "eat my ass",
    "ecchi",
    "ejaculation",
    "erotic",
    "erotism",
    "escort",
    "eunuch",
    "fag",
    "faggot",
    "fecal",
    "felch",
    "fellatio",
    "feltch",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingering",
    "fisting",
    "foot fetish",
    "footjob",
    "frotting",
    "fuck",
    "fuck buttons",
    "fuckin",
    "fucking",
    "fucktards",
    "fudge packer",
    "fudgepacker",
    "futanari",
    "gangbang",
    "gang bang",
    "gay sex",
    "genitals",
    "giant cock",
    "girl on",
    "girl on top",
    "girls gone wild",
    "goatcx",
    "goatse",
    "god damn",
    "gokkun",
    "golden shower",
    "goodpoop",
    "goo girl",
    "goregasm",
    "grope",
    "group sex",
    "g-spot",
    "guro",
    "hand job",
    "handjob",
    "hard core",
    "hardcore",
    "hentai",
    "homoerotic",
    "honkey",
    "hooker",
    "horny",
    "hot carl",
    "hot chick",
    "how to kill",
    "how to murder",
    "huge fat",
    "humping",
    "incest",
    "intercourse",
    "jack off",
    "jail bait",
    "jailbait",
    "jelly donut",
    "jerk off",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jizz",
    "juggs",
    "kike",
    "kinbaku",
    "kinkster",
    "kinky",
    "knobbing",
    "leather restraint",
    "leather straight jacket",
    "lemon party",
    "livesex",
    "lolita",
    "lovemaking",
    "make me come",
    "male squirting",
    "masturbate",
    "masturbating",
    "masturbation",
    "menage a trois",
    "milf",
    "missionary position",
    "mong",
    "motherfucker",
    "mound of venus",
    "mr hands",
    "muff diver",
    "muffdiving",
    "nambla",
    "nawashi",
    "negro",
    "neonazi",
    "nigga",
    "nigger",
    "nig nog",
    "nimphomania",
    "nipple",
    "nipples",
    "nsfw",
    "nsfw images",
    "nude",
    "nudity",
    "nutten",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "orgasm",
    "orgy",
    "paedophile",
    "paki",
    "panties",
    "panty",
    "pedobear",
    "pedophile",
    "pegging",
    "penis",
    "phone sex",
    "piece of shit",
    "pikey",
    "pissing",
    "piss pig",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pole smoker",
    "ponyplay",
    "poof",
    "poon",
    "poontang",
    "punany",
    "poop chute",
    "poopchute",
    "porn",
    "porno",
    "pornography",
    "prince albert piercing",
    "pthc",
    "pubes",
    "pussy",
    "queaf",
    "queef",
    "quim",
    "raghead",
    "raging boner",
    "rape",
    "raping",
    "rapist",
    "rectum",
    "reverse cowgirl",
    "rimjob",
    "rimming",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rusty trombone",
    "sadism",
    "santorum",
    "scat",
    "schlong",
    "scissoring",
    "semen",
    "sex",
    "sexcam",
    "sexo",
    "sexy",
    "sexual",
    "sexually",
    "sexuality",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shibari",
    "shit",
    "shitblimp",
    "shitty",
    "shota",
    "shrimping",
    "skeet",
    "slanteye",
    "slut",
    "s&m",
    "smut",
    "snatch",
    "snowballing",
    "sodomize",
    "sodomy",
    "spastic",
    "spic",
    "splooge",
    "splooge moose",
    "spooge",
    "spread legs",
    "spunk",
    "strap on",
    "strapon",
    "strappado",
    "strip club",
    "style doggy",
    "suck",
    "sucks",
    "suicide girls",
    "sultry women",
    "swastika",
    "swinger",
    "tainted love",
    "taste my",
    "tea bagging",
    "threesome",
    "throating",
    "thumbzilla",
    "tied up",
    "tight white",
    "tit",
    "tits",
    "titties",
    "titty",
    "tongue in a",
    "topless",
    "tosser",
    "towelhead",
    "tranny",
    "tribadism",
    "tub girl",
    "tubgirl",
    "tushy",
    "twat",
    "twink",
    "twinkie",
    "two girls one cup",
    "undressing",
    "upskirt",
    "urethra play",
    "urophilia",
    "vagina",
    "venus mound",
    "viagra",
    "vibrator",
    "violet wand",
    "vorarephilia",
    "voyeur",
    "voyeurweb",
    "voyuer",
    "vulva",
    "wank",
    "wetback",
    "wet dream",
    "white power",
    "whore",
    "worldsex",
    "wrapping men",
    "wrinkled starfish",
    "xx",
    "xxx",
    "yaoi",
    "yellow showers",
    "yiffy",
    "zoophilia",
    "🖕",
}

REVIEW_WORDS = {
    # Mild-to-moderate insults
    "idiot",
    "stupid",
    "dumb",
    "moron",
    "loser",
    "clown",
    "jerk",
    "trash",
    "garbage",
    "pathetic",
    "annoying",
    "embarrassing",
    "fool",

    # Aggressive / hostile phrases
    "shut up",
    "get lost",
    "leave me alone",
    "nobody cares",
    "go away",
    "what is wrong with you",
    "are you stupid",
    "are you dumb",
    "use your brain",
    "learn to read",

    # Moderate profanity
    "damn",
    "hell",
    "crap",
    "pissed off",
    "bullshit",
    "wtf",
    "screw you",

    # --- Spam / raid language ---
    "join our server",
    "discord.gg",
    "free followers",
    "buy followers",
    "cheap services",
    "click my profile",
    "link in bio",

    # --- Harassment patterns ---
    "cry about it",
    "stay mad",
    "cope",
    "seethe",
    "touch grass",

    # --- One-word / low-effort spam ---
    "first",
    "second",
    "third",
    "ratio",
    "skill issue",
    "cope",
    "seethe",
    "cry",
    "cry more",
    "mad",
    "stay mad",
    "cope harder",
    "troll",
    "noob",

    # --- Dismissive trolling ---
    "nobody cares",
    "who asked",
    "who asked you",
    "didn't ask",
    "didnt ask",
    "dont care",
    "don't care",
    "irrelevant",
    "mid",
    "trash",
    "garbage",
    "dead app",
    "this app is dead",
    "this site sucks",
    "waste of time",

    # --- Engagement bait / meme spam ---
    "like if you agree",
    "comment if you agree",
    "share this",
    "boost this",
    "upvote this",
    "spam this",
    "everyone spam",
    "everyone comment",
    "everyone report",

    # --- Raid coordination ---
    "raid this",
    "go raid",
    "mass report",
    "report this",
    "everyone report this",
    "spam the comments",
    "flood this",
    "attack this post",
    "go spam this",

    # --- Platform comparison trolling ---
    "go back to twitter",
    "go back to reddit",
    "go back to tiktok",
    "this isn't twitter",
    "this isn't reddit",
    "this ain't twitter",

    # --- Edgy / low-effort insults ---
    "kys",
    "ez",
    "too easy",
    "get good",
    "skill issue bro",
    "you suck",
    "youre bad",
    "you're bad",
    "bad at this",

    # --- Bot / promo spam ---
    "check my profile",
    "link in bio",
    "join my server",
    "join our server",
    "discord.gg",
    "free followers",
    "buy followers",
    "cheap followers",
    "dm me",
    "message me",
}

def normalize_text(text: str) -> str:
    text = text.lower()

    replacements = {
        "@": "a",
        "0": "o",
        "1": "i",
        "$": "s",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)

    text = re.sub(r"[^a-z0-9\s]", " ", text)
    text = re.sub(r"\s+", " ", text).strip()

    return text


def contains_pattern(text: str, patterns: set[str]) -> str | None:
    for pattern in patterns:
        if pattern in text:
            return pattern
    return None


def moderate_text(text: str, context: str = "general") -> ModerationResult:
    if not text or not text.strip():
        return ModerationResult(
            status="approved",
            score=0.0,
            reason=""
        )

    normalized = normalize_text(text)

    blocked_word = contains_pattern(normalized, PROHIBITED_WORDS)
    if blocked_word:
        if context == "message_content":
            return ModerationResult(
                status="pending",
                score=0.85,
                reason=f"Potentially inappropriate language detected: {blocked_word}"
            )

        return ModerationResult(
            status="rejected",
            score=0.95,
            reason=f"Blocked for prohibited language: {blocked_word}"
        )

    review_word = contains_pattern(normalized, REVIEW_WORDS)
    if review_word:
        return ModerationResult(
            status="pending",
            score=0.65,
            reason=f"Possible inappropriate language requires review: {review_word}"
        )

    return ModerationResult(
        status="approved",
        score=0.05,
        reason=""
    )