# Generated by Django 6.0.3 on 2026-03-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_message_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='risk_level',
            new_name='suspected_risk',
        ),
        migrations.AlterField(
            model_name='message',
            name='classification',
            field=models.CharField(choices=[('Phishing', 'Phishing'), ('Legitimate', 'Legitimate'), ('Unsure', 'Unsure')], max_length=20),
        ),
    ]
