# Generated by Django 6.0.3 on 2026-03-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0006_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='additional_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
