# Generated by Django 6.0.3 on 2026-03-13 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='message_screenshots/'),
        ),
    ]
