# Generated by Django 5.2.12 on 2026-03-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0011_comment_is_flagged_comment_is_removed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='comment',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='requires_human_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='image_moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='message',
            name='moderation_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='pii_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pii_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='pii_review_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='pii_scan_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='requires_human_review',
            field=models.BooleanField(default=False),
        ),
    ]
