# Generated by Django 5.2.12 on 2026-03-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0013_userprofile_moderation_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='redacted_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='redacted_message_screenshots/'),
        ),
    ]
