# Generated by Django 5.2.12 on 2026-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0014_message_redacted_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_moderation_labels',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_relevance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='image_relevance_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
