# Generated by Django 5.2.12 on 2026-03-21 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0015_message_image_moderation_labels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('likely_phishing', 'Likely Phishing'), ('suspicious', 'Suspicious'), ('unclear', 'Unclear'), ('likely_legitimate', 'Likely Legitimate')], max_length=30)),
                ('confidence_score', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('recommended_action', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('analysis_version', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='analyzer.message')),
            ],
        ),
    ]
