# Generated by Django 5.2.12 on 2026-03-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0016_aianalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='detected_domains',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='detected_emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='detected_phone_numbers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='detected_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='impersonated_brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='requested_action',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='scam_category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
