# Generated by Django 5.2.12 on 2026-03-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0017_aianalysis_detected_domains_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='suspected_risk',
        ),
    ]
