# Generated by Django 5.2.12 on 2026-03-27 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0018_remove_message_suspected_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='moderation_score',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='requires_human_review',
        ),
        migrations.RemoveField(
            model_name='message',
            name='moderation_score',
        ),
        migrations.RemoveField(
            model_name='message',
            name='requires_human_review',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='moderation_score',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='requires_human_review',
        ),
    ]
