# Generated by Django 5.2.12 on 2026-03-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0020_userprofilereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='platform',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS / Text Message'), ('Call', 'Phone Call / Voicemail'), ('Social', 'Social Media'), ('App', 'Messaging App'), ('Other', 'Other')], max_length=10),
        ),
    ]
