# Generated by Django 5.2.12 on 2026-04-02 18:19

import analyzer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0021_message_platform_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='message_screenshots/', validators=[analyzer.validators.validate_image]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', validators=[analyzer.validators.validate_image]),
        ),
    ]
