# Generated by Django 5.2.12 on 2026-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0022_alter_message_screenshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='ai_status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='image_processing_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
