# Generated by Django 5.2.12 on 2026-04-03 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0024_message_is_finalized_message_processing_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='processing_failure_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
