# Generated by Django 5.2.12 on 2026-04-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0025_message_processing_failure_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='duplicate_submission_suspected',
            field=models.BooleanField(default=False),
        ),
    ]
