# Generated by Django 5.2.12 on 2026-04-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0026_message_duplicate_submission_suspected'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='admin_flag_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='duplicate_abuse_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rate_limited_flag',
            field=models.BooleanField(default=False),
        ),
    ]
